version: '3'
services:
  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "biu_teamproject_backend"
    ports:
      - "3001:3001"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "biu_teamproject_frontend"
    ports:
      - "3000:3000"
    links:
      - "backend"